import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Footer from '@/app/components/footer'
import NavBar from '@/app/components/navbar'
import { revalidatePath } from 'next/cache'
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <ClerkProvider>
    <html lang="de">
      <body className={inter.className}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
    </ClerkProvider>
  )
}
